name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package
        working-directory: ./TourGuide

      - name: Archive production artifact
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-jar
          path: TourGuide/target/*.jar

      - name: Run unit tests
        run: mvn test
        working-directory: ./TourGuide

      - name: Generate JaCoCo report
        run: mvn jacoco:report
        working-directory: ./TourGuide
