name: Test
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests with Maven
        run: mvn test
